# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an push server image
      inputs:
        containerRegistry: 'DockerHub@TomaT3'
        repository: 'spiritspender'
        command: 'build'
        Dockerfile: '**/pi.dockerfile'
        tags: 'server'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub@TomaT3'
        repository: 'spiritspender'
        command: 'build'
        Dockerfile: '**/pi.client-dockerfile'
        tags: 'client'