version: '3.4'

services:
  spiritspenderserver:
    image: ${DOCKER_REGISTRY-}spiritspenderserver
    build:
      context: .
      dockerfile: SpiritSpenderServer/Dockerfile
    environment:
      MongoDB__Host: mongo
    ports:
      - 5000:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
