name: Build and Deploy to DockerHub
on:
  workflow_dispatch:
  # push:
  #  tags:
  #    - v**

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    # - uses: olegtarasov/get-tag@v2
    #  id: tagName
     # Drafts your next Release notes as Pull Requests are merged into "master"
    - uses: release-drafter/release-drafter@v5
      with:
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: echo verison
      run: echo will be $RESOLVED_VERSION
      # run: echo will build ${{ steps.tagName.outputs.tag }}
    
    # - name: Push tag
    #  uses: mathieudutour/github-tag-action@v4.5
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    custom_tag: $RESOLVED_VERSION
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push Client Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: tomat3/spiritspender
        tags: client-$RESOLVED_VERSION
        dockerfile: ./SpiritSpenderClient/pi.client.Dockerfile
        path: ./SpiritSpenderClient

    - name: Build and push Server Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: tomat3/spiritspender
        tags: server-$RESOLVED_VERSION
        dockerfile: ./SpiritSpenderServer/src/SpiritSpenderServer/pi.dockerfile
        path: ./SpiritSpenderServer/src/SpiritSpenderServer
