# name: build-and-test-server

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   push:
#     paths: 
#       - 'SpiritSpenderServer/**'

# jobs:
#   setup-build-publish-deploy:
#     name: Setup, Build
#     runs-on: ubuntu-latest
#     steps:

#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         lfs: true

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USER }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}

#     - name: Build Server Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: ./SpiritSpenderServer/src
#         file: ./SpiritSpenderServer/src/pi.dockerfile
#         push: false
#         build-args: |
#           versionString=0.0.0
