name: Build and Deploy to DockerHub
on:
  push:
    tags: 
      - 'v**'
  release:
    types: [published]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - id: get_version
      uses: battila7/get-version-action@v2
          
    - name: echo verison
      run: echo "will build ${{ steps.get_version.outputs.version }}"   

    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Client Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./SpiritSpenderClient
        file: ./SpiritSpenderClient/pi.client.Dockerfile
        push: true
        tags: tomat3/spiritspender:client-${{ steps.get_version.outputs.version }}

    - name: Build and push Server Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./SpiritSpenderServer/src
        file: ./SpiritSpenderServer/src/pi.dockerfile
        push: true
        build-args: |
          versionString=${{ steps.get_version.outputs.version-without-v }}
        tags: tomat3/spiritspender:server-${{ steps.get_version.outputs.version }}
