name: build-and-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths-ignore: 
      - 'Doc/**'
      - '.github/workflows/build-and-push-docker-actions.yml'
    branches: 
     - '**'
    tags-ignore:
      - v**

jobs:
  setup-build-publish-deploy:
    name: Setup, Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Client Docker image
      uses: docker/build-push-action@v1
      with:
        repository: tomat3/spiritspender
        dockerfile: ./SpiritSpenderClient/pi.client.Dockerfile
        path: ./SpiritSpenderClient

    - name: Build Server Docker image
      uses: docker/build-push-action@v1
      with:
        repository: tomat3/spiritspender
        dockerfile: ./SpiritSpenderServer/src/SpiritSpenderServer/pi.dockerfile
        path: ./SpiritSpenderServer/src/SpiritSpenderServer
