name: build-and-test-server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
      - 'SpiritSpenderServer/**'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Server Docker image
      uses: docker/build-push-action@v1
      with:
        repository: tomat3/spiritspender
        dockerfile: ./SpiritSpenderServer/src/pi.dockerfile
        path: ./SpiritSpenderServer/src
