name: Build and Deploy to DockerHub
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push Client Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: tomat3/spiritspender
        tags: client
        dockerfile: ./SpiritSpenderClient/pi.client.Dockerfile
        path: ./SpiritSpenderClient

    - name: Build and push Server Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: tomat3/spiritspender
        tags: server
        dockerfile: ./SpiritSpenderServer/src/SpiritSpenderServer/pi.dockerfile
        path: ./SpiritSpenderServer/src/SpiritSpenderServer
